apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-results
  labels:
    app.kubernetes.io/name: shared-storage
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
