apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "worker.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worker.labels" . | nindent 8 }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "worker.env" . | nindent 12 }}
          volumeMounts:
            - name: results
              mountPath: {{ .Values.env.resultsDir }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: results
          persistentVolumeClaim:
            claimName: {{ .Values.resultsPvcName }}
