apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  # NodePort on minikube: Kubernetes allocates a port in the 30000-32767 range on every node;
  # `minikube service frontend` builds a tunnel to it
  type: {{ .Values.service.type }}
  ports:
    # Service port (80)
    - port: {{ .Values.service.port }}
      # nginx port inside the container
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "frontend.labels" . | nindent 4 }}
