apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: worker
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: default
  releaseName: worker
  upgrade:
    force: true
  dependsOn:
    - name: shared-storage
    - name: redis
  chart:
    spec:
      chart: ./helm/worker
      sourceRef:
        kind: GitRepository
        name: pdf-service
      reconcileStrategy: Revision
  values:
    env:
      postgresHost: "pdf-service-dev-postgres.cve0wqswmmc6.eu-central-1.rds.amazonaws.com"
